# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 05:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170812_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bodytext',
            new_name='body_text',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
